// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-EGu8Y5ajz2DqJ0gNo6RqtrrftpS50U8',
    appId: '1:192652912208:web:782adac052283c999b9355',
    messagingSenderId: '192652912208',
    projectId: 'new-iot-8c3f9',
    authDomain: 'new-iot-8c3f9.firebaseapp.com',
    storageBucket: 'new-iot-8c3f9.appspot.com',
    measurementId: 'G-HVZL77KS9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjb8mJgpmENdYg_IP_uVlhGcr_W0dzxa8',
    appId: '1:192652912208:android:7c67a698291bf7e99b9355',
    messagingSenderId: '192652912208',
    projectId: 'new-iot-8c3f9',
    storageBucket: 'new-iot-8c3f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5uX6sDwDw-xSZyRY-JMm74roB6IXY3Ow',
    appId: '1:192652912208:ios:030ed024e3019b7f9b9355',
    messagingSenderId: '192652912208',
    projectId: 'new-iot-8c3f9',
    storageBucket: 'new-iot-8c3f9.appspot.com',
    iosBundleId: 'com.example.iotProject',
  );
}
